package POJOS;

public enum AnemiaType {
    ANEMIC_SYNDROME,
    POSTHEMORRHAGIC_ANEMIA,
    HEMOLYTIC_ANEMIA,
    INHERITED_SPHEROCYTOSIS,
    THALASSEMIA,
    IRON_DEFICIENCY_ANEMIA,
    MEGALOBLASTIC_ANEMIA,
    APLASIC_ANEMIA,
    CHRONIC_DISEASE_ANEMIA,
    POLYCYTHEMIA;

    }
