package diagnosis;

public enum AnemiaType {
    ANEMIC_SYNDROME,
    POSTHEMORRHAGIC_ANEMIA,
    HEMOLYTIC_ANEMIA,
    INHERITED_SPHEROCYTOSIS,
    THALASSEMIA,
    IRON_DEFICIENCY_ANEMIA,
    MEGALOBLASTIC_ANEMIA,
    APLASIC_ANEMIA,
    CHRONIC_DISEASE_ANEMIA,
    POLYCYTHEMIA,


    ANEMIC_SYNDROME_MALE,
    ANEMIC_SYNDROME_FEMALE,
    POSTHEMORRHAGIC_ANEMIA_MALE,
    POSTHEMORRHAGIC_ANEMIA_FEMALE,
    HEMOLYTIC_ANEMIA_MALE,
    HEMOLYTIC_ANEMIA_FEMALE,
    INHERITED_SPHEROCYTOSIS_MALE,
    INHERITED_SPHEROCYTOSIS_FEMALE,
    THALASSEMIA_MALE,
    THALASSEMIA_FEMALE,
    IRON_DEFICIENCY_ANEMIA_MALE,
    IRON_DEFICIENCY_ANEMIA_FEMALE,
    MEGALOBLASTIC_ANEMIA_MALE,
    MEGALOBLASTIC_ANEMIA_FEMALE,
    APLASIC_ANEMIA_MALE,
    APLASIC_ANEMIA_FEMALE,
    CHRONIC_DISEASE_ANEMIA_MALE,
    CHRONIC_DISEASE_ANEMIA_FEMALE,
    POLYCYTHEMIA_MALE,
    POLYCYTHEMIA_FEMALE,



}
