package diagnosis;

public enum AnemiaType {
    ANEMIC_SYNDROME,
    POSTHEMORRAGIC_ANEMIA,
    HEMOLYTIC_ANEMIA,
    INHERITED_SPHEROCYTHOSIS,
    THALASSEMIA,
    IRON_DEFICIENCY_ANEMIA,
    MEGALOBLASTIC_ANEMIA,
    APLASTIC_ANEMIA,
    CHRONIC_ANEMIA,
    POLYCYTHEMIA;

    }
