
package diagnosis;


unit PatientUnit;

import diagnosis.Anemia
import diagnosis.AnemiaType


rule "Anemic Syndrome due to low Hb"
when
    $patient : /patients[detectSymptomValue("Hb")<8]
then
    Anemia a = new Anemia (1, AnemiaType.ANEMIC_SYNDROME);
    $patient.addAnemia(a);
    //do not apply the modify (dont want to consider as a new fact to which the rule can be applied)
    patientsWithAnemicSyndrome.add($patient);
   //System.out.println( $patient + " Anemic Syndrome. ");
end

/*rule "Anemic Syndrome due to tinnitius"
when
    $patient : /patients[detectQuanlitativeSymptom("tinnitius")]
then
    Anemia a = new Anemia (1, AnemiaType.ANEMIC_SYNDROME);
    modify ($patient) {
    addAnemia(a)
    }
    patientsWithAnemicSyndrome.add($patient);
    System.out.println( $patient + " Anemic Syndrome - tinnitius ");
end*/


//9. sin completar, no se hacer compuestas :) o no se obtener el genero :/

rule "Return genderMALE"
when
    $patient : /patients[getGender().equals(gender.MALE)]

then
   patientsMALE.add($patient);

end

//SIN TERMINAR F
rule "9. PosthemorragicAnemiaRBC"
when
    $patient : /patients[detectSymptomValue("RBC")<4.5] //and /patients[getGender().equals("MALE")]

then
    Anemia a = new Anemia (2, AnemiaType.POSTHEMORRAGIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithPosthemorrhagicAnemia.add($patient);

end

rule "10. PosthemorragicAnemiaMCHC"
when
    $patient : /patients[detectSymptomValue("MHCH")<310]

then
    Anemia a = new Anemia (2, AnemiaType.POSTHEMORRAGIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithPosthemorrhagicAnemia.add($patient);

end

rule "11. PosthemorragicAnemiaFe"
when
    $patient : /patients[detectSymptomValue("Fe")<60]

then
    Anemia a = new Anemia (2, AnemiaType.POSTHEMORRAGIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithPosthemorrhagicAnemia.add($patient);

end

rule "16. HemolyticAnemiaMCH>"
when
    $patient : /patients[detectSymptomValue("MCH")>32]

then
    Anemia a = new Anemia (3, AnemiaType.HEMOLYTIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithHemolyticAnemia.add($patient);

end

rule "19. HemolyticAnemiaFe"
when
    $patient : /patients[detectSymptomValue("Fe")>170]

then
    Anemia a = new Anemia (3, AnemiaType.HEMOLYTIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithHemolyticAnemia.add($patient);

end

rule "20. HemolyticAnemiaHaptoglobin"
when
    $patient : /patients[detectSymptomValue("Haptoglobin")<41]

then
    Anemia a = new Anemia (3, AnemiaType.HEMOLYTIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithHemolyticAnemia.add($patient);

end

rule "28. IronDefAnemiaMCH<"
when
    $patient : /patients[detectSymptomValue("MCH")<27]

then
    Anemia a = new Anemia (6, AnemiaType.IRON_DEFICIENCY_ANEMIA);
    $patient.addAnemia(a);
    patientsWithIronDeficiencyAnemia.add($patient);

end

rule "29. IronDefAnemiaFerritin"
when
    $patient : /patients[detectSymptomValue("Ferritin")<12]

then
    Anemia a = new Anemia (6, AnemiaType.IRON_DEFICIENCY_ANEMIA);
    $patient.addAnemia(a);
    patientsWithIronDeficiencyAnemia.add($patient);

end

rule "32. MegaloblasticAnemiaB12"
when
    $patient : /patients[detectSymptomValue("B12")<200]

then
    Anemia a = new Anemia (7, AnemiaType.MEGALOBLASTIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithMegaloblasticAnemia.add($patient);

end

rule "33. MegaloblasticAnemiaFolicAcid"
when
    $patient : /patients[detectSymptomValue("Folic Acid")<2.7]

then
    Anemia a = new Anemia (7, AnemiaType.MEGALOBLASTIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithMegaloblasticAnemia.add($patient);

end

rule "32-33. MegaloblasticAnemiaB12FolicAcid"
when
    $patient : /patients[(detectSymptomValue("Folic Acid")<2.7 || detectSymptomValue("B12")<200)]

then
    Anemia a = new Anemia (7, AnemiaType.MEGALOBLASTIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithMegaloblasticAnemia.add($patient);

end

rule "35. AplasticAnemiaPlaquets"
when
    $patient : /patients[detectSymptomValue("Plaquets")<7.4]

then
    Anemia a = new Anemia (8, AnemiaType.APLASTIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithAplasticAnemia.add($patient);

end

rule "36. AplasticAnemiaLeukocytes"
when
    $patient : /patients[detectSymptomValue("Leukopcytes")<4.5]

then
    Anemia a = new Anemia (8, AnemiaType.APLASTIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithAplasticAnemia.add($patient);

end

rule "37. ChronicDiseaseAnemiaEPO"
when
    $patient : /patients[detectSymptomValue("EPO")<2.6]

then
    Anemia a = new Anemia (9, AnemiaType.CHRONIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithChronicDiseaseAnemia.add($patient);

end

rule "38. ChronicDiseaseAnemiaFerritineMALE"
when
    $patient : /patients[detectSymptomValue("Ferritine")>300 && getGender().equals(gender.MALE)]

then
    Anemia a = new Anemia (9, AnemiaType.CHRONIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithChronicDiseaseAnemia.add($patient);

end

rule "39. ChronicDiseaseAnemiaFerritinFEMALE"
when
    $patient : /patients[detectSymptomValue("Ferritine")>150 && getGender().equals(gender.FEMALE)]

then
    Anemia a = new Anemia (9, AnemiaType.CHRONIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithChronicDiseaseAnemia.add($patient);

end

rule "38-39. ChronicDiseaseAnemiaFerritinFEMALE"
when
    $patient : /patients[(detectSymptomValue("Ferritine")>150 && getGender().equals(gender.FEMALE)) || (detectSymptomValue("Ferritine")>300 && getGender().equals(gender.MALE))]

then
    Anemia a = new Anemia (9, AnemiaType.CHRONIC_ANEMIA);
    $patient.addAnemia(a);
    patientsWithChronicDiseaseAnemia.add($patient);

end

rule "40. PolycythemiaHb"
when
    $patient : /patients[(detectSymptomValue("Hb")>15.3 && getGender().equals(gender.FEMALE)) || (detectSymptomValue("Hb")>17.5 && getGender().equals(gender.MALE))]

then
    Anemia a = new Anemia (10, AnemiaType.POLYCYTHEMIA);
    $patient.addAnemia(a);
    patientsWithPolycythemia.add($patient);

end

rule "41. PolycythemiaPVM"
when
    $patient : /patients[(detectSymptomValue("PVM")>47 && getGender().equals(gender.FEMALE)) || (detectSymptomValue("PVM")>53 && getGender().equals(gender.MALE))]

then
    Anemia a = new Anemia (10, AnemiaType.POLYCYTHEMIA);
    $patient.addAnemia(a);
    patientsWithPolycythemia.add($patient);

end

rule "43. PolycythemiaGlucocorticoids"
when
    $patient : /patients[detectSymptomValue("Glucocorticoids")>25]

then
    Anemia a = new Anemia (10, AnemiaType.POLYCYTHEMIA);
    $patient.addAnemia(a);
    patientsWithPolycythemia.add($patient);

end

rule "45. PolycythemiaRBC"
when
    $patient : /patients[(detectSymptomValue("RBC")>5.3 && getGender().equals(gender.FEMALE)) || (detectSymptomValue("RBC")>5.9 && getGender().equals(gender.MALE))]

then
    Anemia a = new Anemia (10, AnemiaType.POLYCYTHEMIA);
    $patient.addAnemia(a);
    patientsWithPolycythemia.add($patient);

end