package diagnosis;
dialect  "mvel"

rule "templateDRL"
    when
    then
end

/*package atm;

unit OperationUnit;

rule "authorization of operations"
when
    $operation : /operations[verified == true, date_expired == false, correctPin == true, tries == Tries.NOT_EXPIRED, balance >= price, limit >= price]
then
    // IF I WANT TO DEBUG THE CODE, I CAN PRINT HERE WHATEVER I WANT System.out.println( op );
    System.out.println( $operation + " authorized. ");
    // Student, please try to do this instead of modify like before. What is the difference?
    //$operation.setAuthorized(true);
    // or
    modify ($operation) {
    setAuthorized(true)
    }
    System.out.println( $operation + " authorized. ");
end

rule "invalid verification"
when
    $operation : /operations[verified == false]
then
    System.out.println( $operation + " not authorized due to lack of verification. ");
    modify ($operation) { setAuthorized(false)}
    operationsUnauthorizedNotVerified.add($operation);
end

rule "exceeded limit"
when
    $operation : /operations[limit < price]
then
    System.out.println( $operation + " not authorized due to limit. ");
    modify ($operation) { setAuthorized(false)}
    operationsUnauthorizedExceededLimit.add($operation);
end

query FindAuthorizedOperations
    $operations : /operations[ authorized == true]
end*/
